# Generated by Django 3.2 on 2023-01-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mailinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
