# Generated by Django 3.2 on 2023-01-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremail',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
