# Generated by Django 3.2 on 2023-01-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230109_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsmall', models.IntegerField(blank=True, null=True)),
                ('small', models.IntegerField(blank=True, null=True)),
                ('medium', models.IntegerField(blank=True, null=True)),
                ('large', models.IntegerField(blank=True, null=True)),
                ('xlarge', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='large',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='small',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='xlarge',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='xsmall',
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='products.ProductSize'),
        ),
    ]
