# Generated by Django 3.2 on 2023-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230110_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeStock',
            new_name='ProductSize',
        ),
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=True),
        ),
    ]
