# Generated by Django 3.2 on 2023-01-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230110_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('total_sold', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsmall', models.IntegerField(blank=True, null=True)),
                ('small', models.IntegerField(blank=True, null=True)),
                ('medium', models.IntegerField(blank=True, null=True)),
                ('large', models.IntegerField(blank=True, null=True)),
                ('xlarge', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_sold',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.AddField(
            model_name='sizestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stock', to='products.product'),
        ),
        migrations.AddField(
            model_name='regularstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_stock', to='products.product'),
        ),
    ]
